### ISSUE TITLE
How can we get user thumb from finger print machine?

### ISSUE THREAD

**Issue by SnguonTheara** [bulentv/js_zklib#5]
I see that we can get user information and attendant. How about user thumb? Can we set user information with thumb?
Please help me.

**Comment by windgaucho** [comment]
I would like to know that too. Currently I have developed a microsoft vb.net system that is using the zk sdk, but I would like to migrate it to node.js.
Can I listen to real time events (like the user fingerprint) using this package?

**Comment by bulentv** [comment]
@SnguonTheara, @windgaucho 

Unfortunately I couldn't find enough information regarding to transfer or query the fingerprint/face info from/to devices on the web.

**Comment by windgaucho** [comment]
What operations I am allowed to do using this package?

add/delete users to/from the device?

**Comment by bulentv** [comment]
No, unfortunately it is limited to read operations.
Contributions are welcomed.

**Comment by shubhamoy** [comment]
@bulentv This issue can be closed as the current pr #6 does this. Attn: @SnguonTheara

**Comment by bulentv** [comment]
Thanks.

**Comment by windgaucho** [comment]
Thank you @shubhamoy !!!!!!!!!!!!!!!!!!

**Comment by windgaucho** [comment]
There is any docs about this new methods? :)

**Comment by shubhamoy** [comment]
@windgaucho You can check this [commit](https://github.com/bulentv/js_zklib/pull/6/commits/3d2fe446d544deaeeffb2172b5fe4b53b4702cb8). Apart from that feel free to post your query.

**Comment by windgaucho** [comment]
Last night I was trying to connect to F8 zk fingerprint.
I tried to do a simple test with the code that you have in the readme.md and I was able to connect to my reader device, but I was getting an error that says that the gettime function does not exist, can you advice me about this error?

**Comment by shubhamoy** [comment]
Preliminary it appears that it's quite possible that the device's firmware might not be supporting the said method. Try checking the official documentation and codebase.

**Comment by windgaucho** [comment]
ok, I will do that and let you know, thanks for this library !!

**Comment by windgaucho** [comment]
@shubhamoy I can confirm that the method gettime works perfect in my device.
I was doing ZK.getTime() instead of ZK.gettime(). Note that is not camel case, that was the error.

Now I am getting the following error when I execute the sample code that is in the readme:
``
var ZKLib = require("zklib");
    ZK = new ZKLib({
      ip : "192.168.5.11", 
      port : 4370,
      inport : 5200
    });
    
    // connect to access control device
    ZK.connect( function() {
    
      // read the time info from th device
      ZK.getTime( function(err, t) {
        console.log("Device clock's time is " + t.toString());
        
        // disconnect from the device
        ZK.disconnect();
      });
    });
``

the error message is:
``
W20180301-19:21:20.112(-3)? (STDERR) TypeError: cb is not a function
W20180301-19:21:20.113(-3)? (STDERR)     at Socket.<anonymous> (/home/test-zklib/node_modules/zklib/zklib/zklib.js:39:7)
W20180301-19:21:20.113(-3)? (STDERR)     at Object.onceWrapper (events.js:317:30)
W20180301-19:21:20.114(-3)? (STDERR)     at emitTwo (events.js:126:13)
W20180301-19:21:20.117(-3)? (STDERR)     at Socket.emit (events.js:214:7)
W20180301-19:21:20.118(-3)? (STDERR)     at UDP.onMessage (dgram.js:658:8)
``
the error is fired when call the ZK.disconnect().
What I am doing wrong?
